# Generated by Django 5.0.4 on 2024-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/&d'),
        ),
    ]
