# Generated by Django 5.0.4 on 2024-05-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
