# Generated by Django 5.0.4 on 2024-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cvview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
